name: Build Android Kernel

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32z-dev libelf-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev adb fastboot

    - name: Download kernel and toolchains
      run: |
        git clone https://github.com/LineageOS/android_kernel_google_msm-4.9.git --depth=1
        git clone https://github.com/LineageOS/android_prebuilts_clang_kernel_linux-x86_clang-r416183b.git --depth=1
        git clone https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9.git --depth=1
        git clone https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9.git --depth=1

    - name: Set Environment Variables
      run: |
        echo "PATH=$(echo $GITHUB_WORKSPACE/android_prebuilts_clang_kernel_linux-x86_clang-r416183b/bin):$(echo $GITHUB_WORKSPACE/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9/bin):$(echo $GITHUB_WORKSPACE/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9/bin):$PATH" >> $GITHUB_ENV
        echo "CC=clang" >> $GITHUB_ENV
        echo "CLANG_TRIPLE=aarch64-linux-gnu-" >> $GITHUB_ENV
        echo "CROSS_COMPILE=aarch64-linux-android-" >> $GITHUB_ENV
        echo "CROSS_COMPILE_ARM32=arm-linux-androideabi-" >> $GITHUB_ENV
        echo "ARCH=arm64" >> $GITHUB_ENV

    - name: Build Kernel
      run: |
        cd android_kernel_google_msm-4.9
        make O=out CC=clang ARCH=arm64 CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-android- CROSS_COMPILE_ARM32=arm-linux-androideabi- sdm845_defconfig
        make -j$(nproc) V=1 O=out CC=clang ARCH=arm64

    - name: Upload Kernel
      uses: actions/upload-artifact@v3
      with:
        name: kernel
        path: android_kernel_google_msm-4.9/out/arch/arm64/boot
