name: Build Android Kernel

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: Setup Python
      uses: actions/setup-python@v5.1.0
      with:
            python-version: '3.10'

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y llvm-15 python-pip tree bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32z-dev libelf-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev adb fastboot
        pip install ast-grep-cli
        
    - name: Download kernel and toolchains
      run: |
        git clone https://github.com/cupid-development/android_kernel_xiaomi_sm8450.git --depth=1
        git clone https://github.com/LineageOS/android_prebuilts_clang_kernel_linux-x86_clang-r416183b.git --depth=1
        git clone https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9.git --depth=1
        git clone https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9.git --depth=1

    - name: Set Environment Variables
      run: |
        echo "PATH=$(echo $GITHUB_WORKSPACE/android_prebuilts_clang_kernel_linux-x86_clang-r416183b/bin):$(echo $GITHUB_WORKSPACE/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9/bin):$(echo $GITHUB_WORKSPACE/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9/bin):$PATH" >> $GITHUB_ENV
        echo "CC=clang" >> $GITHUB_ENV
        echo "CLANG_TRIPLE=aarch64-linux-android-" >> $GITHUB_ENV
        echo "CROSS_COMPILE=aarch64-linux-android-" >> $GITHUB_ENV
        echo "CROSS_COMPILE_COMPA=arm-linux-androideabi-" >> $GITHUB_ENV
        echo "ARCH=arm64" >> $GITHUB_ENV

    - name: Build Kernel
      run: |
        cd android_kernel_xiaomi_sm8450
        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main
        cat KernelSU/kernel/export_symbol.txt | awk '{sub("[ \t]+","");print "  "$0}' >> android/abi_gki_aarch64
        ast-grep -U -p '$$$ check_exports($$$) {$$$}' -r '' scripts/mod/modpost.c
        ast-grep -U -p 'check_exports($$$);' -r '' scripts/mod/modpost.c
        sed -i '/config KSU/,/help/{s/default y/default m/}' drivers/kernelsu/Kconfig
        echo "drivers/kernelsu/kernelsu.ko" >> android/gki_aarch64_modules
        make LTO=thin CC=clang ARCH=arm64 CROSS_COMPILE=aarch64-linux-android- gki_defconfig
        make -j$(nproc) obj-m LTO=thin ARCH=arm64 CC=clang  CROSS_COMPILE=aarch64-linux-android-

    - name: Upload Kernel
      uses: actions/upload-artifact@v4.3.1
      with:
        name: kernel
        path: |
              android_kernel_xiaomi_sm8450/out/arch/arm64/*
              android_kernel_xiaomi_sm8450/KernelSU/kernel/Kconfig
